### ISSUE TITLE
google fonts load over http not https causing mixed-content warnings

### ISSUE THREAD

**Issue by bitssg** [OCA/website-themes#12]

**Comment by tarteo** [comment]
I don't think so. The fonts are loaded protocol relative https://github.com/OCA/website-themes/blob/1afdcc8c2e3217274f1985d94617a52693229612/website_theme_flexible/templates/options/fonts.xml#L11 

Our company have used this module many times on different websites and never had this problem. For example one of the websites loads: https://fonts.googleapis.com/css?family=Ubuntu:300|Titillium+Web:400

But I can make a PR in 20 seconds to enforce https, soooo...

**Comment by bitssg** [comment]
Thank you @tarteo I will close this
