### ISSUE TITLE
website_theme_flexible: Unable to select font

### ISSUE THREAD

**Issue by treviser** [OCA/website-themes#3]
Environment: Server Ubuntu 16.04 LTS, Odoo 11.0 CE 2018-03-21, Firefox Quantum 59.0.1 (64-bit) on Ubuntu 17.10 Desktop Xorg

The font selection window does not adapt in size and the font selector only shows the 5 first fonts in alphabetic order:
![selection_021](https://user-images.githubusercontent.com/1814941/37702830-121e84cc-2cf4-11e8-844d-b3d7e1ac8dd5.png)

Browser error:

![selection_022](https://user-images.githubusercontent.com/1814941/37702869-31d87b2e-2cf4-11e8-80c9-65edb1a23c02.png)

**Comment by pedrobaeza** [comment]
All these tests would be good when in PR, as the module was there for a lot of time...

**Comment by treviser** [comment]
If you addressed me, I have to apologize, you may remember that I'm not a developer and have no environment setup yet to test PRs, and secondly, I only learned about this very nice module this morning from twitter :-)
And it was not my intention to test it, but to use it in production for a new customer ;-)

**Comment by pedrobaeza** [comment]
OK, no worry, I understand.

**Comment by tarteo** [comment]
@treviser The error you get is probably not due to website_theme_flexible. You can search fonts by typing the font you want. You can browse fonts here https://fonts.google.com/.
The selection box is limited because there are over 800 fonts; if this was not the case you'll be scrolling a long time before you find the font you want.

**Comment by treviser** [comment]
@tarteo I also tried to directly enter a particular font (Roboto for example) and the screenshot is taken from that situation.

**Comment by tarteo** [comment]
![image](https://user-images.githubusercontent.com/10028499/37704368-e80ef8d8-2cf8-11e8-9f1c-9e699de97ad6.png)

I tested it in Chrome and Firefox and in both browser I can select a font just fine. Can you describe the problem further please maybe using a video?

**Comment by treviser** [comment]
@tarteo Ok, I'm getting closer. It is related to my other issue: https://github.com/OCA/website-themes/issues/2
It is necessary to have the developer mode activated in order to customize the theme (and the fonts) properly. But the installation of the module destroyed the developer mode with assets, I can't use the developer mode with assets anymore even after uninstalling module, updating all modules and restarting Odoo. But the developer mode without assets still works, and when this mode is activated, it is possible to select the fonts as you described.

**Comment by tarteo** [comment]
@treviser I cannot reproduce the situation you are describing (it works with and without developer mode) on my environment. 
With assets it's indeed giving an error but that's another issue. The assets issue needs more research to give a clear answer for that (it's probably due to the inline less and css in the assets bundle).

**Comment by treviser** [comment]
@tarteo Maybe I should test it in a fresh database. Anyway, so we could close this issue, but you can confirm the other issue https://github.com/OCA/website-themes/issues/2 as this is a show stopper, correct? Thanks.

**Comment by tarteo** [comment]
@treviser Only if somebody wants to see the assets, yes.

**Comment by treviser** [comment]
@tarteo Of course, but how am I supposed to develop a website if I can't use the developer mode with assets anymore?

**Comment by tarteo** [comment]
@treviser I know, it's an issue... :stuck_out_tongue: I only said that it's only a show stopper when you want to see the assets... the theme works fine when you don't use debug=assets. The theme has a field where you can make custom CSS changes for the time.

**Comment by treviser** [comment]
@tarteo It would be ok if the debug=asset mode would work again after uninstalling the module. This way I'm not able to qualify how dangerous it is, especially after the database went productive.

**Comment by tarteo** [comment]
@treviser ok, than we agree with each other. Thanks for reporting the bug! ❤️
