### ISSUE TITLE
Translatable Fields do not appear in Transifex

### ISSUE THREAD

**Issue by Fuchur777** [OCA/website-themes#5]
`https://www.transifex.com/oca/OCA-website-themes-11-0/translate/#nl_NL/website_theme_flexible`
No fileds to translate while there are a few that should show up.

@pedrobaeza something to do with new Repository? Or other issue?

**Comment by pedrobaeza** [comment]
I see them: https://www.transifex.com/oca/OCA-website-themes-11-0/dashboard/

**Comment by Fuchur777** [comment]
I dont see any translateble fields, can you add a screenshot of what you see?
