### ISSUE TITLE
website_flexible_theme: menu bar double

### ISSUE THREAD

**Issue by ghost** [OCA/website-themes#7]
I dont know which infos you need for this bug.

![screenshot_20180716_204617](https://user-images.githubusercontent.com/40705043/42777217-a6f282be-8939-11e8-8e83-219fa5da1bf4.png)

**Comment by ghost** [comment]
ok it happend when i click it to a sticky menu bar

**Comment by pedrobaeza** [comment]
Is this reproducible on runbot? https://runbot.odoo-community.org/runbot/186/11.0

**Comment by ghost** [comment]
sorry. i have no experience with runbot and dont know how i to use it because on this installation the theme isnt installed.
could i install more modules ?

**Comment by ghost** [comment]
i mean the module is not in the app-list available

**Comment by pedrobaeza** [comment]
Sorry, incorrect link:

https://runbot.odoo-community.org/runbot/258/11.0

(but it will take about 20 minutes for rebuilding the instance)

**Comment by ghost** [comment]
How to use this runbot?

**Comment by pedrobaeza** [comment]
See the test part (section 4) on https://odoo-community.org/page/review

**Comment by ghost** [comment]
Sorry i 
![screenshot_20180718_204516](https://user-images.githubusercontent.com/40705043/42901353-ab61de38-8acb-11e8-8ac8-d1aca460df84.png)
 dont get it :-(
That i see:

**Comment by pedrobaeza** [comment]
Click on "Force rebuild" and wait for the build to get completed.

**Comment by ghost** [comment]
Ok now its complete ? and how could i log in ?

**Comment by pedrobaeza** [comment]
admin / admin

**Comment by ghost** [comment]
ok, thank you, i have to give up. i dont know where i can login to this runbot build. I'm too stupid for that

**Comment by tarteo** [comment]
This will fix it: https://github.com/OCA/website-themes/pull/8

**Comment by pedrobaeza** [comment]
Fixed already

**Comment by tarteo** [comment]
@Axel-G `#wrap { margin-top: 45px }` put this into the CSS tab to set your desired content top margin.
